version: '3.8'

services:
  flask_generator:
    build:
      context: ./flask_generator
    ports:
      - "5000:5000"
    networks:
      - app-network

  fastapi_invoker:
    build:
      context: ./fastapi_invoker
    ports:
      - "8000:8000"
    depends_on:
      - flask_generator
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
